[project]
name = 'stacks-flash-loans'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.flasher]
path = 'contracts/flasher.clar'
clarity_version = 4
epoch = 3.3

[contracts.flashloans-trait]
path = 'contracts/flashloans-trait.clar'
clarity_version = 4
epoch = 3.3

[contracts.mock-flash-recipient]
path = 'contracts/mock-flash-recipient.clar'
clarity_version = 4
epoch = 3.3

[contracts.mock-token]
path = 'contracts/mock-token.clar'
clarity_version = 4
epoch = 3.3

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
